dset ^ElenaIsenTest.dat
undef -9.99E8
title ERAInterim
xdef 1 linear 231.0 0.5
ydef 91 linear -9.0 0.5
zdef 34 linear 265.0 5.0
tdef 32 linear 00:00z28Aug1985 6hr
vars 46
utm        34    99 tangential velocity (m s^-1)
vrm        34    99 radial velocity (m s^-1)
aam        34    99 traditional absolute angular momentum (m^2 s^-1)
pvm        34    99 vertical component of potential voticity (m^2 K kg^-1 s^-1)
sgm        34    99 pseudo density (kg m^-2 K^-1)
mgm        34    99 Montgomery potential [m**2 s**-2] (profile)
prm        34    99 Pressure [Pa] (profile)
Mxm        34    99 azimuthal derivative of Montgomery streamfunction (m^2 s^-2)
utmm       34    99 pseudo-density-weighted zonal mean of tangential velocity (m s^-1)
svm        34    99 pseudo density (kg m^-2 K^-1)
vrmm       34    99 pseudo-density-weighted zonal mean of radial velocity (m s^-1)
aammm      34    99 pseudo-density-weighted zonal mean of traditional absolute angular momentum (m^2 s^-1)
pvmm       34    99 pseudo-density-weighted zonal mean of vertical component of potential voticity (m^2 K kg^-1 s^-1)
pvflx      34    99 [s][P'v'] (m^2 s^-2)
pvmflx     34    99 [sP*v*] (m^2 s^-2)
sVaMa      34    99 ['M'] (sv)
sVaUa      34    99 ['U'] (sv)
sVmaMma    34    99 [sv*M*] (kg m K^-1 s^-2)
sVmaUma    34    99 [sv*U*] (kg K^-1 s^-2)
paMxa      34    99 [p'M¦Ë'] (Pa m^2 s^-2)
sWmaMma    34    99 [sv*M*] (kg m K^-1 s^-2)
sWmaUma    34    99 [sv*U*] (kg K^-1 s^-2)
EPdivU     34    99 divergence in YZ plane (vecY * m^-1 or vecZ * Pa^-1)
EPmdivU    34    99 divergence in YZ plane (vecY * m^-1 or vecZ * Pa^-1)
EPdivM     34    99 divergence in YZ plane (vecY * m^-1 or vecZ * Pa^-1)
EPmdivM    34    99 divergence in YZ plane (vecY * m^-1 or vecZ * Pa^-1)
EPyM       34    99 meridional component of Eliassen-Palm vector EPy (kg m K^-1 s^-2)
EPzM       34    99 vertical component of Eliassen-Palm vector EPz (Pa m)
EPySM      34    99 scaled EPy by multiplying actual length representing 1m (kg m K^-1 s^-2)
EPzSM      34    99 scaled EPz by multiplying actual length representing 1K (Pa m)
EPmyM      34    99 meridional component of EP vector EPy -[sv*M*] (kg m K^-1 s^-2)
EPmz1M     34    99 adiabatic vertical component of EP vector EPz  [p'M¦Ë']/g (kg s^-2)
EPmz2M     34    99 diabatic vertical component of EP vector EPz -[sw*M*] (kg s^-2)
EPmySM     34    99 scaled EPy by multiplying actual length representing 1m (kg m K^-1 s^-2)
EPmz1SM    34    99 scaled adiabatic EPz by multiplying actual length representing 1K (Pa m)
EPmz2SM    34    99 scaled  diabatic EPz by multiplying actual length representing 1K (Pa m)
EPyU       34    99 meridional component of Eliassen-Palm vector EPy (kg m K^-1 s^-2)
EPzU       34    99 vertical component of Eliassen-Palm vector EPz (Pa m)
EPySU      34    99 scaled EPy by multiplying actual length representing 1m (kg m K^-1 s^-2)
EPzSU      34    99 scaled EPz by multiplying actual length representing 1K (Pa m)
EPmyU      34    99 meridional component of EP vector EPy -[sv*U*]r (kg m K^-1 s^-2)
EPmz1U     34    99 adiabatic vertical component of EP vector EPz  [p'M¦Ë']/g (kg s^-2)
EPmz2U     34    99 diabatic vertical component of EP vector EPz -[sw*U*]r (kg s^-2)
EPmySU     34    99 scaled EPy by multiplying actual length representing 1m (kg m K^-1 s^-2)
EPmz1SU    34    99 scaled adiabatic EPz by multiplying actual length representing 1K (Pa m)
EPmz2SU    34    99 scaled  diabatic EPz by multiplying actual length representing 1K (Pa m)
endvars
